POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "username": "testuser3",
  "password": "123456789"
}

###

POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "username": "testuser3",
  "password": "123456789"
}
